### ISSUE TITLE
buildtasks/bin/generate-buildenv exits with non-zero exit code when awscli not installed - should just be warning

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1118]
When running buildtasks, `bin/generate-buildenv` creates a file including all the relevant info regarding the build environment (useful for auditing and bug hunting). However, if `awscli` isn't installed, it exits with non-zero exit code:
```
ImportError: No module named awscli
```

Also it checks for ec2 data (for when being run on AWS). This creates and ugly traceback when being run elsewhere. This should also just be a warning...
```
Traceback (most recent call last):
  File "/usr/bin/ec2metadata", line 59, in <module>
    main()
  File "/usr/bin/ec2metadata", line 55, in main
    ec2metadata.display(metaopts)
  File "/usr/lib/python2.7/dist-packages/ec2metadata/__init__.py", line 91, in display
    m = EC2Metadata()
  File "/usr/lib/python2.7/dist-packages/ec2metadata/__init__.py", line 32, in __init__
    raise Error("could not establish connection to: %s" % self.addr)
ec2metadata.Error: could not establish connection to: 169.254.169.254
Traceback (most recent call last):
  File "<string>", line 1, in <module>
```

**Comment by JedMeister** [comment]
I vaguely recall addressing this already?! Until I can confirm, moving to v16.0 - should be closed ASAP if already addressed, or addressed if not! :smile:

**Comment by JedMeister** [comment]
The issue the title relates to was fixed some time ago, namely here: https://github.com/turnkeylinux/buildtasks/commit/0586cd14beda2b01d523a3bda700ded27d4db1b7#diff-bca3c1af1c3337271520d6fad4ec9f70R63

The (unrelated) ami-id gathering code (via ec2metadata) also implemented in that same commit was unreliable. I have since fixed that too: https://github.com/turnkeylinux/buildtasks/commit/4c06f5db65ba55c48d6a8d99568fbb1b09faac81
