### ISSUE TITLE
Drupal8 appliance domain inithook throwing error

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1135]
The domain setting inithook on the Drupal8 appliance is throwing an error:
```
Progress...
Traceback (most recent call last):
  File "/usr/lib/inithooks/bin/drupal8.py", line 90, in <module>
    main()
  File "/usr/lib/inithooks/bin/drupal8.py", line 87, in main
    system('/usr/lib/inithooks/bin/drupalconf.sh -e {EMAIL} -p {PASSWORD} -d {DOMAIN}'.format(EMAIL=email, PASSWORD=password, DOMAIN=domain))
  File "/usr/lib/python2.7/dist-packages/executil.py", line 56, in system
    raise ExecError(command, exitcode)
executil.ExecError: non-zero exitcode (210) for command: /usr/lib/inithooks/bin/drupalconf.sh -e admin@example.net -p PASSWORD_I_SET -d www\\\.example\\\.net
```
I set the email as `admin@example.net`, password as `PASSWORD_I_SET` and domain as `www.example.net`.

**Comment by JedMeister** [comment]
False alarm! Ends up I had over provisioned my local storage and MySQL was crashing due to insufficient free HDD space.
