### ISSUE TITLE
Omeka inithook erroring

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1148]
```
ERROR 1146 (42S02) at line 1: Table 'omeka.entities' doesn't exist
Traceback (most recent call last):
  File "/usr/lib/inithooks/bin/omeka.py", line 71, in <module>
    main()
  File "/usr/lib/inithooks/bin/omeka.py", line 67, in main
    m.execute('UPDATE omeka.entities SET email=\"%s\" WHERE id=1' % email)
  File "/usr/lib/inithooks/bin/mysqlconf.py", line 73, in execute
    system("mysql --defaults-file=%s -B -e '%s'" % (DEBIAN_CNF, query))
  File "/usr/lib/python2.7/dist-packages/executil.py", line 56, in system
    raise ExecError(command, exitcode)
executil.ExecError: non-zero exitcode (1) for command: mysql --defaults-file=/etc/mysql/debian.cnf -B -e 'UPDATE omeka.entities SET email="admin@example.com" WHERE id=1'
```

**Comment by JedMeister** [comment]
FWIW, it still actually seems to work ok, but is spitting out the above error...

**Comment by JedMeister** [comment]
Closed by https://github.com/turnkeylinux-apps/omeka/commit/4bb443681c4f5dab9e9aecb0b27987d836c4cc49
