### ISSUE TITLE
hubtools: hub-list-backups errors

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1173]
`hub-list-backups` appears to not be working.

```
# hub-list-backups
Traceback (most recent call last):
  File "/usr/bin/hub-list-backups", line 93, in <module>
    main()
  File "/usr/bin/hub-list-backups", line 80, in main
    backups = hub.backups.get()
  File "/usr/lib/python2.7/dist-packages/hub/backups.py", line 61, in get
    return [ BackupRecord(backup) for backup in r ]
  File "/usr/lib/python2.7/dist-packages/hub/backups.py", line 26, in __init__
    self.skpp = self._key_has_passphrase(response['key'])
  File "/usr/lib/python2.7/dist-packages/hub/backups.py", line 39, in _key_has_passphrase
    keypacket.parse(key, "")
  File "/usr/lib/python2.7/dist-packages/hub/keypacket.py", line 104, in parse
    cipher_repeats)
  File "/usr/lib/python2.7/dist-packages/hub/keypacket.py", line 40, in _repeat
    input = f(input)
  File "/usr/lib/python2.7/dist-packages/hub/keypacket.py", line 102, in <lambda>
    decrypted = _repeat(lambda v: _cipher(cipher_key).decrypt(v),
  File "/usr/lib/python2.7/dist-packages/hub/keypacket.py", line 49, in _cipher
    return AES.new(cipher_key, AES.MODE_CBC)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 94, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: IV must be 16 bytes long
```
Workaround is to use `tklbam-list`:

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux/hubtools/commit/1a00d9ed524c45ebf5b07489fc82fc30504adf51
