### ISSUE TITLE
Ansible - Python3 bug in Debian

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1324]
Following the update to Python3 (see #1300) I've noticed a weird bug during testing, namely, when I tried to test, this was the result:

```
ansible@J-ANSIBLE ~$ ansible localhost -m ping
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7eff3b932268>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7eff3b932268>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7eff3b932268>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7eff3b932268>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7eff3b932268>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```
As you can see, it's still works, but it's really ugly with that stacktrace and on face value, it's not clear that it worked ok.

After having a bit of a search, I discovered the bug within the [Ansible tracker](https://github.com/ansible/ansible/issues/21982) and that it's actually a [bug in Python](https://bugs.python.org/issue29519). The relevant Debian issue is [#918716](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918716).

Unfortunately, it appears that a fix has not yet been backported for Debian Stretch. I did find a [backported python3-weakref package](https://packages.debian.org/sid/python3-backports.weakref) which likely includes the fix, but it's only available in Buster (and Sid).

However, after a bit of digging, I discovered that the [pyfits package](https://packages.debian.org/stretch/python3-pyfits) also includes a copy of `weakref.py`. Install (with it's dependencies) adds an additional ~25MB, which is not ideal, but it does resolve the issue. When I test ping, I now get:

```
ansible@J-ANSIBLE ~$ ansible localhost -m ping
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

Hopefully no other appliances are hitting this issue within the default weakref.py in the Python3 Stretch package. But if we run into any others before they fix this, this weird but functional workaround may be the answer?!

**Comment by JedMeister** [comment]
Closed as per most recent comment (i.e. inclusion of pyfits package).
