### ISSUE TITLE
LXC (and other headless builds) - Confconsole causing stacktrace in the inithooks log

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1485]
While testing a completely unrelated issues on an LXC server, I just noticed that there is a stacktrace in the logs (both journal and `/var/log/inithooks.log`) when inithooks tries to launch Confconsole:

```
Jul  6 04:11:54 jed-test-prestashop inithooks: Inithook run completed, now starting confconsole
INFO: Inithook run completed, now starting confconsole
Jul  6 04:11:56 jed-test-prestashop inithooks[80]: /usr/lib/inithooks/run: line 76:    94 Killed                  tail -f $LOGFILE > /dev/$TTY
Jul  6 04:11:56 jed-test-prestashop inithooks[80]: #033)0#033[1;24r#033[m#017#033[4l#033[?7h#033[?1000h#033[39;49m#033[39;49m#033[m#017#033[H#033[J#033[23d#033[0;10;1m#017#033[36m#033[44m#033[J#033[H TurnKey GNU/Linux Configuration Console#033[K
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:  ────────#033[37m#033[47m┌─────────#033[34m#033[47mJED-TEST-PRESTASHOP appliance services#033[37m#033[47m───────────#033[0;10m#017#033[30m#033[47m┐#033[0;10;1m#017#033[36m#033[44m──────────#033[K#033[3;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[3;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[4;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[4;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[5;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[5;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[6;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[6;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[7;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[7;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[8;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[8;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[9;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[9;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[10;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[10;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[11;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[11;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[12;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[12;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[13;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[13;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[14;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[14;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[15;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[15;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[16;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[16;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[17;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[17;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[18;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[18;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[19;9H#033[1K #033[37m#033[47m├──────────────────────────────────────────────────────────#033[0;10m#017#033[30m#033[47m┤#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[20;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[25X#033[20;36H#033[0;10;1m#017#033[37m#033[44m<#033[33m#033[44m #033[37m#033[44mQ#033[33m#033[44muit #033[37m#033[44m>#033[0;10m#017#033[30m#033[47m#033[25X#033[20;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[21;9H#033[1K #033[37m#033[47m└#033[0;10m#017#033[30m#033[47m──────────────────────────────────────────────────────────┘#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[22;11H#033[1K #033[30m#033[40m#033[60X#033[22;72H#033[36m#033[44m#033[K#033[20;38H#033[39;49m#033[m#017#033[4;12H#033[30m#033[47mWeb:#033[4;24Hhttp://192.168.1.109#033[5;24Hhttps://192.168.1.109#033[6;24Hhttps://192.168.1.109/administration#033[7;12HWeb shell:  https://192.168.1.109:12320#033[8;12HWebmin:     https://192.168.1.109:12321#033[9;12HAdminer:    https://192.168.1.109:12322#033[10;12HSSH/SFTP:   root@192.168.1.109 (port 22)#033[12;12HTKLBAM (Backup and Migration):  NOT INITIALIZED#033[17;21HTurnKey Backups and Cloud Deployment#033[18;25Hhttps://hub.turnkeylinux.org#033[20;38H#033[39;49m#033[m#017#033[22;71H#033[?1000l#033[24;1H#015#033)0#033[1;24r#033[m#017#033[4l#033[?7h#033[?1000h#033[39;49m#033[39;49m#033[m#017#033[H#033[J#033[23d#033[0;10;1m#017#033[36m#033[44m#033[J#033[H TurnKey GNU/Linux Configuration Console#033[K
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:  ────────#033[37m#033[47m┌────────────────────#033[34m#033[47mCaught exception#033[37m#033[47m──────────────────────#033[0;10m#017#033[30m#033[47m┐#033[0;10;1m#017#033[36m#033[44m──────────#033[K#033[3;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[3;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[4;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[4;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[5;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[5;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[6;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[6;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[7;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[7;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[8;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[8;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[9;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[9;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[10;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[10;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[11;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[11;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[12;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[12;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[13;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[13;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[14;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[14;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[15;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[15;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[16;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[16;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[17;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[17;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[18;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[58X#033[18;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[19;9H#033[1K #033[37m#033[47m├──────────────────────────────────────────────────────────#033[0;10m#017#033[30m#033[47m┤#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[20;9H#033[1K #033[37m#033[47m│#033[0;10m#017#033[30m#033[47m#033[25X#033[20;36H#033[0;10;1m#017#033[37m#033[44m<#033[33m#033[44m  ok  #033[37m#033[44m>#033[0;10m#017#033[30m#033[47m#033[25X#033[20;69H│#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[21;9H#033[1K #033[37m#033[47m└#033[0;10m#017#033[30m#033[47m──────────────────────────────────────────────────────────┘#033[0;10;1m#017#033[30m#033[40m  #033[36m#033[44m#033[K#033[22;11H#033[1K #033[30m#033[40m#033[60X#033[22;72H#033[36m#033[44m#033[K#033[20;39H#033[39;49m#033[m#017#033[3;13H#033[30m#033[47mTraceback (most recent call last):   File#033[4;12H"/usr/bin/confconsole", line 661, in loop     new_dialog#033[5;12H= method()   File "/usr/bin/confconsole", line 396, in#033[6;12Husage     button_label=default_button_label)   File#033[7;12H"/usr/bin/confconsole", line 124, in msgbox#033[8;12Htitle=title, ok_label=button_label)   File#033[9;12H"/usr/bin/confconsole", line 94, in _wrapper     ret =#033[10;12Hmethod("#033[11;12H" + text, *args, **kws)   File#033[12;12H"/usr/lib/python3/dist-packages/dialog.py", line 3028,#033[13;12Hin msgbox     kwargs)   File#033[14;12H"/usr/lib/python3/dist-packages/dialog.py", line 1717,#033[15;12Hin _widget_with_no_output     code, output =#033[16;12Hself._perform(args, **kwargs)   File#033[17;12H"/usr/lib/python3/dist-packages/dialog.py", line 1504,#033[18;12Hin _perform     args_file)   File#033[19;64H#033[0;10;1m#017#033[34m#033[47m57%#033[20;39H#033[39;49m#033[m#017#033[22;71H#033[?1000l#033[24;1H#015Traceback (most recent call last):
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/bin/confconsole", line 661, in loop
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     new_dialog = method()
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/bin/confconsole", line 396, in usage
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     button_label=default_button_label)
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/bin/confconsole", line 124, in msgbox
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     title=title, ok_label=button_label)
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/bin/confconsole", line 94, in _wrapper
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     ret = method("\n" + text, *args, **kws)
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/lib/python3/dist-packages/dialog.py", line 3028, in msgbox
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     kwargs)
Jul  6 04:11:56 jed-test-prestashop inithooks[80]: dialog.DialogError: dialog-like terminated due to an error: the dialog-like program exited with status 3 (which was passed to it as the DIALOG_ERROR environment variable). Sometimes, the reason is simply that dialog was given a height or width parameter that is too big for the terminal in use. Its output, with leading and trailing whitespace stripped, was:
Jul  6 04:11:56 jed-test-prestashop inithooks[80]: During handling of the above exception, another exception occurred:
Jul  6 04:11:56 jed-test-prestashop inithooks[80]: Traceback (most recent call last):
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/bin/confconsole", line 729, in <module>
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     main()
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/bin/confconsole", line 724, in main
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     tc.loop()
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/bin/confconsole", line 671, in loop
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     self.console.msgbox("Caught exception", sio.getvalue())
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/bin/confconsole", line 124, in msgbox
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     title=title, ok_label=button_label)
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/bin/confconsole", line 94, in _wrapper
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     ret = method("\n" + text, *args, **kws)
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/lib/python3/dist-packages/dialog.py", line 3028, in msgbox
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     kwargs)
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/lib/python3/dist-packages/dialog.py", line 1717, in _widget_with_no_output
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     code, output = self._perform(args, **kwargs)
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/lib/python3/dist-packages/dialog.py", line 1504, in _perform
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     args_file)
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/lib/python3/dist-packages/dialog.py", line 1469, in _handle_program_exit
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     child_output_rfd)
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:   File "/usr/lib/python3/dist-packages/dialog.py", line 1421, in _wait_for_program_termination
Jul  6 04:11:56 jed-test-prestashop inithooks[80]:     child_output.strip()))
Jul  6 04:11:56 jed-test-prestashop inithooks[80]: dialog.DialogError: dialog-like terminated due to an error: the dialog-like program exited with status 3 (which was passed to it as the DIALOG_ERROR environment variable). Sometimes, the reason is simply that dialog was given a height or width parameter that is too big for the terminal in use. Its output, with leading and trailing whitespace stripped, was:
INFO: Confconsole completed, now exiting
Jul  6 04:11:56 jed-test-prestashop inithooks: Confconsole completed, now exiting
```

The issue is that on headless deployments, the inithooks output is redirected to the log file (then the logfile is piped back to the default TTY). That works fine for the inithooks because they run non-interactively, either they're preseeded by the user, or by the fence.

However, Confconsole always runs interactively, but as it's being redirected to a file, it can't find the terminal size...

Note I've only tagged container (i.e. Proxmix/LXC) but it applies to all headless builds.

**Comment by JedMeister** [comment]
The fix is to only run confconsole when output is not redirected - within the [`run`](https://github.com/turnkeylinux/inithooks/blob/master/run) file.
