### ISSUE TITLE
Wireguard - inithooks don't run interactively when launched from the Hub

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1646]
[Phil reported on the forums](https://www.turnkeylinux.org/forum/support/tue-20210921-1353/wireguard-setup) that when launched from the Hub, the `wg0` interface isn't initialised by default. When trying to create a client, he received this message:

```
wg-quick: `/etc/wireguard/wg0.conf' does not exist

Traceback (most recent call last):

File "/usr/local/bin/wireguard-addclient", line 171, in <module>
     add_client(args.client_name, args.allowed_ips)

File "/usr/local/bin/wireguard-addclient", line 129, in add_client
     server_addr, server_port, taken_ips = parse_config('/etc/wireguard/wg0.conf')

File "/usr/local/bin/wireguard-addclient", line 22, in parse_config with open(path, 'r') as fob:

FileNotFoundError: [Errno 2] No such file or directory: '/etc/wireguard/wg0.conf'
```

It turns out that the Wireguard inithook doesn't run when pre-seeded (by the Hub). We'll need to work out how to fix that, but in the meantime, you can workaround the issue by manually invoking the Wireguard inithook like this:

```
/usr/lib/inithooks/bin/wireguard.py
```
(You could re-run the whole "firstboot" initialisation process via the `turnkey-init` command.)

**Comment by JedMeister** [comment]
Temporarily updated the Wireguard doc page to note this bug. See https://github.com/turnkeylinux-apps/wireguard/commit/381ea2928a8de7fb52f59b679b87278d4605bd1a

**Comment by JedMeister** [comment]
This should be resolved by https://github.com/turnkeylinux-apps/wireguard/pull/10

**Comment by JedMeister** [comment]
After some more digging and testing, it appears that this was not in fact fixed :sob: . However this should actually finalise the fix: https://github.com/turnkeylinux-apps/wireguard/pull/15

**Comment by JedMeister** [comment]
closed by: https://github.com/turnkeylinux-apps/wireguard/pull/15
