### ISSUE TITLE
nodejs - npm needs updating

### ISSUE THREAD

**Issue by BuildTheRobots** [turnkeylinux/tracker#171]
As of February 27, 2014 npm no longer supports its self-signed certificates. [1]
This causes things like `npm install` to fail throwing Error: "Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN" 

The advice[2] to update using `npm install npm -g` fails too (see below).

Advice greatly appreciated.

```
root@nodejs ~# npm config set ca ""
root@nodejs ~# npm install npm -g
npm http GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-1.4.4.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-1.4.4.tgz
npm WARN package.json github-url-from-git@1.1.1 No repository field.
npm ERR! error rolling back Error: Refusing to delete: /usr/local/bin/npm not in /usr/local/lib/node_modules/npm
npm ERR! error rolling back     at clobberFail (/usr/local/src/node-v0.10.20-linux-x64/lib/node_modules/npm/lib/utils/gently-rm.js:41:12)
npm ERR! error rolling back     at next (/usr/local/src/node-v0.10.20-linux-x64/lib/node_modules/npm/lib/utils/gently-rm.js:27:14)
npm ERR! error rolling back     at /usr/local/src/node-v0.10.20-linux-x64/lib/node_modules/npm/lib/utils/gently-rm.js:36:12
npm ERR! error rolling back     at Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back  npm@1.4.4 { [Error: Refusing to delete: /usr/local/bin/npm not in /usr/local/lib/node_modules/npm] code: 'EEXIST', path: '/usr/local/bin/npm' }
npm ERR! Refusing to delete: /usr/local/bin/npm not in /usr/local/lib/node_modules/npm
File exists: /usr/local/bin/npm
Move it away, and try again. 

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm" "-g"
npm ERR! cwd /root
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/bin/npm
npm ERR! code EEXIST
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
```

[1] - http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more
[2] - http://stackoverflow.com/questions/9626990/receiving-error-error-ssl-error-self-signed-cert-in-chain-while-using-npm

**Comment by JedMeister** [comment]
THis should be resolved as of v14.0 release. If you still have issues with v14.0 please open a new issue.
