### ISSUE TITLE
TKLBAM restore issue within webmin

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1717]
This failure occurred from webmin - during testing of the webmin-tklbam module update for v17.0

Despite the error message, the paths complained about actually exist.

It was reproducible within webmin (I reproduced it 3 restore/restore-rollback cycles in a row), but when I tried to reproduce it on the CLI, I couldn't?!

So either there is/was some race condition, or an edge case issue that somehow resolved itself cycling restore/restore-rollback.

It is worth noting though that the webmin module runs `tklbam-restore-rollback --force` whereas when I did it via CLI I omitted the force switch (I retried with `--force` later but worked ok.

Here's the stacktrace from webmin-tklbam logs:
```
> tklbam-restore-rollback --force
Traceback (most recent call last):
File "/usr/lib/tklbam/rollback.py", line 107, in rollback_files
local_rec = DirIndex.Record.frompath(change.path)
File "/usr/lib/tklbam/dirindex.py", line 35, in frompath
st = os.lstat(path)
OSError: [Errno 2] No such file or directory: '/etc/.git/objects/63'
Traceback (most recent call last):
File "/usr/lib/tklbam/rollback.py", line 107, in rollback_files
local_rec = DirIndex.Record.frompath(change.path)
File "/usr/lib/tklbam/dirindex.py", line 35, in frompath
st = os.lstat(path)
OSError: [Errno 2] No such file or directory: '/etc/.git/objects/92'
error: rollback_files raised an exception:
Traceback (most recent call last):
File "/usr/lib/tklbam/rollback.py", line 150, in rollback
method()
File "/usr/lib/tklbam/rollback.py", line 125, in rollback_files
raise Error("caught %d exceptions during rollback_files" % exceptions)
Error: caught 2 exceptions during rollback_files
Traceback (most recent call last):
File "/bin/tklbam-restore-rollback", line 76, in <module>
main()
File "/bin/tklbam-restore-rollback", line 73, in main
rollback.rollback()
File "/usr/lib/tklbam/rollback.py", line 158, in rollback
raise Error("caught %d exceptions during rollback" % exceptions)
rollback.Error: caught 1 exceptions during rollback
```

**Comment by JedMeister** [comment]
Not sure if this is still an issue or not? I'll move it to v18.0 just in case...

**Comment by JedMeister** [comment]
I'm closing this. If someone hits it again, please reopen - or open a new issue.
