### ISSUE TITLE
gitlab 16.10 - error 500

### ISSUE THREAD

**Issue by gromov-io** [turnkeylinux/tracker#1736]
Ruby:         ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
 GitLab:       13.11.4 (cea3c37b30e) FOSS
 GitLab Shell: 13.17.0
 PostgreSQL:   12.6

it is very difficult for me to write this, but it is impossible to use this product in this form (((
Constantly 500 errors, not one of the methods found on the Internet does not help to solve the problem.

login as root - err 500
page runners - err 500
saving settings - err 500
after restarting the machine, gitlab-runsvdir crashes

please tell me what needs to be done to fix these problems?

```
OpenSSL::Cipher::CipherError ():
  
lib/gitlab/database.rb:342:in `block in transaction'
lib/gitlab/database.rb:341:in `transaction'
app/services/application_settings/update_service.rb:50:in `update_settings'
lib/gitlab/metrics/instrumentation.rb:160:in `block in update_settings'
lib/gitlab/metrics/method_call.rb:27:in `measure'
lib/gitlab/metrics/instrumentation.rb:160:in `update_settings'
app/services/application_settings/update_service.rb:12:in `execute'
lib/gitlab/metrics/instrumentation.rb:160:in `block in execute'
lib/gitlab/metrics/method_call.rb:27:in `measure'
lib/gitlab/metrics/instrumentation.rb:160:in `execute'
app/controllers/application_controller.rb:531:in `disable_usage_stats'
app/controllers/application_controller.rb:517:in `set_usage_stats_consent_flag'
app/controllers/application_controller.rb:463:in `block in set_current_context'
lib/gitlab/application_context.rb:70:in `block in use'
lib/gitlab/application_context.rb:70:in `use'
lib/gitlab/application_context.rb:27:in `with_context'
app/controllers/application_controller.rb:454:in `set_current_context'
lib/gitlab/metrics/elasticsearch_rack_middleware.rb:16:in `call'
lib/gitlab/middleware/rails_queue_duration.rb:33:in `call'
lib/gitlab/metrics/rack_middleware.rb:16:in `block in call'
lib/gitlab/metrics/transaction.rb:56:in `run'
lib/gitlab/metrics/rack_middleware.rb:16:in `call'
lib/gitlab/request_profiler/middleware.rb:17:in `call'
lib/gitlab/jira/middleware.rb:19:in `call'
lib/gitlab/middleware/go.rb:20:in `call'
lib/gitlab/etag_caching/middleware.rb:21:in `call'
lib/gitlab/middleware/multipart.rb:172:in `call'
lib/gitlab/middleware/read_only/controller.rb:50:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
lib/gitlab/middleware/handle_malformed_strings.rb:21:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'
lib/gitlab/middleware/request_context.rb:21:in `call'
config/initializers/fix_local_cache_middleware.rb:11:in `call'
lib/gitlab/middleware/rack_multipart_tempfile_factory.rb:21:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:76:in `call'
lib/gitlab/middleware/release_env.rb:12:in `call'
```

**Comment by JedMeister** [comment]
My guess is insufficient resources. Please ensure that you have given it at least 4GB RAM (8GB recommended), plus at least 2 CPUs.

If you already have done that and the issue persists, then the only thing I can recommend is reinstalling GitLab (note all config will be reset to default):

```
apt update
apt purge gitlab-ce -y
apt install gitlab-ce -y
```

**Comment by OnGle** [comment]
Closing for inactivity and being out of date / no longer relevant
