### ISSUE TITLE
Fixclock script broken restoring to latest Turnkey Core

### ISSUE THREAD

**Issue by kiwibrew** [turnkeylinux/tracker#1780]
Restore of an older Turnkey Core system on the latest Turnkey Core image breaks at Fixclock.

```
sh: 1: /etc/tklbam/hooks.d/fixclock: not found
Traceback (most recent call last):
  File "/usr/bin/tklbam-restore", line 554, in <module>
    main()
  File "/usr/bin/tklbam-restore", line 533, in main
    hooks.restore.post()
  File "/usr/lib/tklbam/hooks.py", line 81, in post
    self._run("post")
  File "/usr/lib/tklbam/hooks.py", line 73, in _run
    _run_hooks(self.LOCAL_HOOKS, (self.name, state))
  File "/usr/lib/tklbam/hooks.py", line 42, in _run_hooks
    (fpath, " ".join(args), e.exitcode))
hooks.HookError: `/etc/tklbam/hooks.d/fixclock restore post` non-zero exitcode (127)
```

This happens because the script references /usr/bin/python, which doesn't exist. This Turnkey Core instance only has /usr/bin/python2 or /usr/bin/python3.

**Comment by JedMeister** [comment]
Hi @kiwibrew

Thanks for your report and apologies my response is a little slow. I've been unwell but am on the mend now.

You are absolutely correct. As you note, the reason why that occurs is that the newer release no long has a `/usr/bin/python` (only `python2` or `python3`). FYI, `/usr/bin/python` always pointed to `python2` and the Python foundation recommend not using it anymore (i.e. use `/usr/bin/python3` explicitly and once we get to v4, `/usr/bin/python4`).

We have updated the fixclock script to use a `/usr/bin/python2` shebang, but will need to update that as python2 support is pretty much dead (py2 is EOL).

Even though we've updated it, the copy of the fixclock script you have, is in your backup! I recommend explicitly excluding it from the restore. Another option would be to do your restore in 2 stages and tweak it manually in between.

To exclude it from your restore:
```
tklbam-restore BACKUP_ID --limits="-/etc/tklbam/hooks.d/fixclock"
```
(where `BACKUP_ID` is your actual backup ID number).

Or to do the restore in 2 stages (with a tweak in the middle):
```
mkdir -p /tklbam-dump
tklbam-restore BACKUP_ID --raw-download=/tklbam-dump
sed -i "\|^#\!/usr/bin/python|s|python|python2|" /tklbam-dump/etc/tklbam/hooks.d/fixclock
tklbam-restore /tklbam-dump
```
(again where `BACKUP_ID` is your actual backup ID number).
