### ISSUE TITLE
Confconsole broken on bookworm (Python 3.9 -> 3.11)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1829]
In initial testing of v18.0beta `confconsole` is broken. When I try to run it I get:

```
root@tkldev18-beta ~# confconsole
Traceback (most recent call last):
  File "/usr/bin/confconsole", line 739, in <module>
    main()
  File "/usr/bin/confconsole", line 712, in main
    pm = plugin.PluginManager(PLUGIN_PATH,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/confconsole/plugin.py", line 183, in __init__
    current_plugin = Plugin(file_path, module_globals)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/confconsole/plugin.py", line 78, in __init__
    self.module = imp.load_module(self.module_name, module_fob,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imp.py", line 235, in load_module
    return load_source(name, filename, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imp.py", line 172, in load_source
    module = _load(spec)
             ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/confconsole/plugins_d/Lets_Encrypt/get_certificate.py", line 11, in <module>
    import dns_01
ModuleNotFoundError: No module named 'dns_01'
```
Seems to be related to changes in relative import in python?

@OnGle - hand balling this one to you! :smile:

**Comment by JedMeister** [comment]
New package (`2.0.6+2+gc814701`) built and uploaded to `bookworm-testing`.
