### ISSUE TITLE
tkldev-changelog failing on Typo3

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1899]
`tkldev-changelog` is currently failing on the changelog of typo3:
```
Traceback (most recent call last):
  File "/usr/bin/tkldev-changelog-extractor", line 127, in <module>
    primary = process_changelog(args.changelog)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/tkldev-changelog-extractor", line 83, in process_changelog
    changes[current_v][-1] += line
    ~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```
I'm not really sure what is wrong, but I've manually worked around it for now...

**Comment by OnGle** [comment]
@JedMeister

Pretty sure this got fixed already.

**Comment by JedMeister** [comment]
Thanks. Yes you are right - I just double checked to be sure and it worked fine...
