### ISSUE TITLE
Consider including `ec2-instance-connect` package in AWS MP AMIs

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1915]
I note that Debian (and therefore TurnKey) are listed as supported OS for the use of [EC2 Instance Connect](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-set-up.html). It appears that on Ubuntu it is provided by a package named [`ec2-instance-connect`](https://packages.ubuntu.com/jammy/ec2-instance-connect). Unfortunately it does not appear to be in the Debian repos (I assume why Debian isn't supported). I'm not 100% sure what the rationale for that is, but perhaps we could consider adding it.

FWIW I did download the upstream source ([`aws-ec2-instance-connect-config`](https://github.com/aws/aws-ec2-instance-connect-config/tree/master)) and tried building it on TurnKey (via pool) but it failed, ending with this output:

```
dpkg-buildpackage => dh build --with systemd
dpkg-buildpackage => dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dpkg-buildpackage =>    dh_update_autotools_config
dpkg-buildpackage =>    dh_auto_configure
dpkg-buildpackage => dh_auto_configure: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dpkg-buildpackage =>    dh_auto_build
dpkg-buildpackage => dh_auto_build: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dpkg-buildpackage => 	make -j1
dpkg-buildpackage => make[1]: Entering directory '/home/build/ec2-instance-connect-0+2022.9.13+19.54.03+551c73e8'
dpkg-buildpackage => make[1]: 'default' is up to date.
dpkg-buildpackage => make[1]: Leaving directory '/home/build/ec2-instance-connect-0+2022.9.13+19.54.03+551c73e8'
dpkg-buildpackage =>    dh_auto_test
dpkg-buildpackage => dh_auto_test: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dpkg-buildpackage =>  fakeroot debian/rules binary
dpkg-buildpackage => dh binary --with systemd
dpkg-buildpackage => dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dpkg-buildpackage =>    dh_testroot
dpkg-buildpackage =>    dh_prep
dpkg-buildpackage =>    dh_auto_install --destdir=debian/ec2-instance-connect/
dpkg-buildpackage => dh_auto_install: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dpkg-buildpackage =>    dh_install
dpkg-buildpackage => dh_install: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dpkg-buildpackage => dh_install: warning: Cannot find (any matches for) "ec2-instance-connect/*" (tried in ., debian/tmp)
dpkg-buildpackage => 
dpkg-buildpackage => dh_install: warning: ec2-instance-connect missing files: ec2-instance-connect/*
dpkg-buildpackage => dh_install: error: missing files, aborting
dpkg-buildpackage => make: *** [debian/rules:7: binary] Error 25
dpkg-buildpackage => dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/libdeckdebuild/__init__.py", line 157, in deckdebuild
    proctee_joined(["chroot",  chroot, "su", user, "-l", "-c", build_cmd],
  File "/usr/lib/python3/dist-packages/libdeckdebuild/proctee.py", line 115, in proctee_joined
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['chroot', '/var/lib/deckdebuilds/chroots/ec2-instance-connect-0+2022.9.13+19.54.03+551c73e8', 'su', 'build', '-l', '-c', 'cd ec2-instance-connect-0+2022.9.13+19.54.03+551c73e8;dpkg-buildpackage -d -uc -us -b -rfakeroot']' returned non-zero exit status 2.
# umount -f /var/lib/deckdebuilds/chroots/ec2-instance-connect-0+2022.9.13+19.54.03+551c73e8/dev/shm
# deck -D /var/lib/deckdebuilds/chroots/ec2-instance-connect-0+2022.9.13+19.54.03+551c73e8

error: recently built package `ec2-instance-connect=0+2022.9.13+19.54.03+551c73e8' missing from cache
```

**Comment by JedMeister** [comment]
downgrading this to wishlist as a closer looks makes me think that this isn't something that would be relevant to most of our users...
