### ISSUE TITLE
tklbam-backup to ssh or scp address doesn't work

### ISSUE THREAD

**Issue by jeff-dagenais** [turnkeylinux/tracker#318]
***(tried posting this in the support forum but was rejected as SPAM! :-( )***

Using turnkey-core-13.0-wheezy-amd64

```
​​tklbam-backup --disable-resume --debug --address=scp://myuser@myhost.example.com:22/tklbam/$(uname -n)
```
Tried many variations (including ssh://), but showing my last attempt with user, fqdn and port specified. All yield the same error:

```
...
# export PASSPHRASE=$(cat /var/lib/tklbam/secret)
# duplicity --verbosity=5 --archive-dir=/var/cache/duplicity cleanup --force scp://myuser@myhost.example.com:22/tklbam/jfdtest
Backend error detail: Traceback (most recent call last):
  File "/usr/lib/tklbam/deps/bin/duplicity", line 1405, in <module>
    with_tempdir(main)
  File "/usr/lib/tklbam/deps/bin/duplicity", line 1398, in with_tempdir
    fn()
  File "/usr/lib/tklbam/deps/bin/duplicity", line 1249, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/commandline.py", line 999, in ProcessCommandLine
    globals.backend = backend.get_backend(args[0])
  File "/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/backend.py", line 158, in get_backend
    return _backends[pu.scheme](pu)
  File "/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/backends/sshbackend.py", line 115, in __init__
    raise BackendException("ssh connection to %s:%d failed: %s" % (parsed_url.hostname,portnumber,e))
BackendException: ssh connection to myhost.example.com:22 failed: Unknown server myhost.example.com

BackendException: ssh connection to myhost.example.com:22 failed: Unknown server myhost.example.com
Traceback (most recent call last):
  File "/usr/bin/tklbam-backup", line 510, in <module>
    main()
  File "/usr/bin/tklbam-backup", line 464, in main
    log=_print)
  File "/usr/lib/tklbam/duplicity.py", line 235, in __call__
    cleanup_command.run(target.secret, target.credentials)
  File "/usr/lib/tklbam/duplicity.py", line 114, in run
    raise Error("non-zero exitcode (%d) from backup command: %s" % (exitcode, str(self)))
duplicity.Error: non-zero exitcode (23) from backup command: duplicity --verbosity=5 --archive-dir=/var/cache/duplicity cleanup --force scp://myuser@ myhost.example.com:22/tklbam/jfdtest
```
Any clue?

**Comment by JedMeister** [comment]
There is a dependency missing... Try installing python-paramiko i.e.:
````
apt-get update && apt-get install python-paramiko
````
I discovered this issue myself when trying to do a backup to SSH target TBH I had meant to document it somewhere but got sidetracked. I spoke with Liraz (the TKLBAM 'Daddy') about it and this is what he said:

> TKLBAM supports all of these different backends ... including SSH
through Duplicity but as you found out getting that to work might
require installing some extra components.
>
> It would definitely be a good idea to document any issues you run into.
A simple oneliner in the documentation might save someone else alot of
headache.

So sorry that I didn't document it and save you the headache... :(

**Comment by JedMeister** [comment]
FWIW I have just issued a pull request to update the docs. I also manually updated the docs on the website: http://www.turnkeylinux.org/docs/tklbam/man/tklbam-backup.

Please close this issue if my above instructions solve your issue.

**Comment by jeff-dagenais** [comment]
Thanks for your answer. I had already found that this dependency could be related and had installed it. Without `python-paramiko`, the error is

```
UnsupportedBackendScheme: scheme not supported in url: scp://root@myhost.example.com:22/tklbam/jfdtest
```

... about documenting a missing dependency, perhaps the code could detect missing backend support dependencies and simply mention: "Please refer to tklbam man pages" or something.

**Comment by jeff-dagenais** [comment]
Found out the problem. It is a paramiko issue with ecdsa:
https://github.com/paramiko/paramiko/issues/67
https://github.com/paramiko/paramiko/issues/46

I'm on wheezy, the paramiko version in wheezy-backport is not high enough. Tried the packages in jessie https://packages.debian.org/jessie/python-paramiko, but they failed dependency requirements at the python-six package.

So here's my workaround:
1. On another ssh client machine which had already connected to this same server, I copied the line about that server in the client's ~/.ssh/known_hosts, which happened to be rsa.
2. replaced the entries on the tklbam client's /root/.ssh/known_hosts with the one copied above.
3. manually ssh connect to the ssh server so the RSA<->IP line be created
4. now that only RSA is implied in my known_hosts, the tklbam command works.

**Comment by JedMeister** [comment]
Great work @jeff-dagenais 

Thanks for posting your findings... FWIW I don't recall having any of those issues when I backed up my Debian (Wheezy) desktop with TKLBAM but I must admit that it was a while ago...

**Comment by jeff-dagenais** [comment]
If the involved systems choose to establish trust based on the RSA host keys, then you would be fine. So it's a coincidence of the server and client used in the scenario. In my scenario it was a turnkey-13.0 client and a freenas 9.3 ssh server.

**Comment by JedMeister** [comment]
Ah ok. Well that probably explains it then. I backed up a Debian Wheezy desktop to a TurnKey server...

**Comment by jeff-dagenais** [comment]
Found a better workaround. It involves doing a complete ssh host key scan to add ALL of the remote's host keys into the source user's known_hosts file:

(as root)
`ssh-keyscan backup.target.host.net >> ~/.ssh/known_hosts`

Of course, you should verify the keyscan resulting fingerprints of the remote system:

`ssh-keygen -l -f .ssh/known_hosts`

To recap, doing the above and `apt-get install python-paramiko` solves the problem!

Once documentation is updated, this issue should be closed.
Cheers!
