### ISSUE TITLE
[Jessie] eJabberd appliance won't build due to Speeqe issues

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#395]
`conf.d/main` is failing on [this line](https://github.com/turnkeylinux-apps/ejabberd/blob/master/conf.d/main#L36):
````
# $WEBROOT/manage.py syncdb --noinput

Traceback (most recent call last):
  File "/var/www/django/speeqeweb/manage.py", line 3, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager
````
A little research suggests that this is related to a [Django changes](https://docs.djangoproject.com/en/1.4/releases/1.4/#updated-default-project-layout-and-manage-py) 

`execute_manager` was deprecated in django 1.4 and was removed entirely in django 1.6. Theoretically `execute_manager` can be replaced with `execute_from_command_line` so we end up with this:
````
#!/usr/bin/env python
#django generated file
from django.core.management import execute_from_command_line
try:
    import settings # Assumed to be in the same directory.
except ImportError:
    import sys
    sys.stderr.write("Error: Can't find the file 'settings.py' in the directory containing %r. It appears you've customized things.\nYou'll have to run django-admin.py, passing it your settings module.\n(If the file settings.py does indeed exist, it's causing an ImportError somehow.)\n" % __file__)
    sys.exit(1)

if __name__ == "__main__":
    execute_from_command_line(settings)
````
But that doesn't resolve the issue as I now get:
````
# $WEBROOT/manage.py syncdb --noinput

Traceback (most recent call last):
  File "/var/www/django/speeqeweb/manage.py", line 12, in <module>
    execute_from_command_line(settings)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 384, in execute_from_command_line
    utility = ManagementUtility(argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 182, in __init__
    self.prog_name = os.path.basename(self.argv[0])
TypeError: 'module' object has no attribute '__getitem__'
````

**Comment by JedMeister** [comment]
Issue also reported upstream...

**Comment by JedMeister** [comment]
I haven't heard anything back from Speeqe upstream and I assume that the update would be non-trivial so I am considering replacing Speeqe with [CandyChat](https://candy-chat.github.io/candy/)...

**Comment by JedMeister** [comment]
Django 1.4 is supported until Oct 2015 so perhaps we may look at retaining Speeqe at least until then...

**Comment by JedMeister** [comment]
ejabberd appliance currently deferred from v14.0 release so retargeting to "on ice"

**Comment by JedMeister** [comment]
closing as ejabberd appliance has been discontinued
