### ISSUE TITLE
[Jessie] OSQA won't build

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#402]
It appears that there is a now a GitHub repo [here](https://github.com/dzone/OSQA) which has commits from earlier this year. However I just tested building this (with a few tweaks for Jessie) and it errors. At a glance iot appears that it is because OSQA code does not support current Debian Django (v1.7)

My updated code is [here](https://github.com/JedMeister/osqa/tree/updated-for-jessie), and here is the tail fo the stacktrace when I tried to build:
````
+ cd /var/www/osqa
+ python manage.py syncdb --all --noinput
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
Syncing...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/dist-packages/south/management/commands/syncdb.py", line 82, in handle_noargs
    old_app_store, cache.app_store = cache.app_store, SortedDict([
AttributeError: 'Apps' object has no attribute 'app_store'
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
make: *** [build/stamps/root.patched] Error 1
````

**Comment by JedMeister** [comment]
As per #76 OSQA does not appear to be completely dead, but it also doesn't appear to be current or under active development. Apparently there is a beta version that works but currently it does not pass TurnKey quality control. As such this issue is being closed. 

If/when OSQA provide a stable release we will re-release this appliance.
