### ISSUE TITLE
[Jessie] Prestashop inithook not working properly

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#436]
I have just tested the Prestashop app and the inithook (`/usr/lib/inithooks/bin/prestashop.py`) did not work properly. When I ran `turnkey-init` it didn't ask for domain and password. When I ran `prestashop.py` directly it asked for email then errorred:
````
Traceback (most recent call last):
  File "/usr/lib/inithooks/bin/prestashop.py", line 94, in <module>
    main()
  File "/usr/lib/inithooks/bin/prestashop.py", line 62, in main
    min_length=8)
TypeError: get_password() got an unexpected keyword argument 'min_length'
````

**Comment by JedMeister** [comment]
Dgging in a little deeper there were a few other things that needed tweaking. Now done (awaiting merge).
