### ISSUE TITLE
Build error (osqa): requires legacy django

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#76]
```
+ python manage.py syncdb --all --noinput
Traceback (most recent call last):
File "manage.py", line 13, in <module>
execute_manager(settings)
File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 459, in execute_manager
utility.execute()
File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
klass = load_command_class(app_name, subcommand)
File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 69, in load_command_class
module = import_module('%s.management.commands.%s' % (app_name, name))
File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
__import__(name)
File "/usr/lib/python2.7/dist-packages/south/management/commands/__init__.py", line 13, in <module>
from south.management.commands.syncdb import Command as SyncCommand
File "/usr/lib/python2.7/dist-packages/south/management/commands/syncdb.py", line 17, in <module>
from south.db import dbs
File "/usr/lib/python2.7/dist-packages/south/db/__init__.py", line 78, in <module>
db = dbs[DEFAULT_DB_ALIAS]
KeyError: 'default'
make: *** [build/stamps/root.patched] Error 1

```

**Comment by JedMeister** [comment]
It seems that OSQA now has a GitHub repo. It appears to be alive...

See here: https://github.com/dzone/OSQA

**Comment by JedMeister** [comment]
The software does not appear to be completely dead, but it also doesn't appear to be current or under active development. Apparently there is a beta version that works but currently it does not pass TurnKey quality control. As such this issue is being closed.
