### ISSUE TITLE
Lamby's reproducible builds packages won't build for Stretch (using current deckdebuild)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#910]
It turns out that `deckdebuild` can't handle `debian/control` files where the build-depends are split over multiple lines. 

In the short term, I'll work around this by moving them all back to one line. [**update:** I have confirmed that this worked.] But the file is certainly much cleaner looking as it currently is. And I would argue that it's not a reasonable assumption to make. So it should be addressed for v15.0

FWIW here's the error:
````
root@da-shiz pools/stretch# pool get . tklbam-squid
### BUILDING PACKAGE: tklbam-squid=2.7.STABLE9-2.1turnkey+36+gebf182e
###           SOURCE: /turnkey/fab/pools/stretch/.pool/stocks/tklbam-squid#pkg/checkout/
Traceback (most recent call last):
  File "/usr/lib/deckdebuild/wrapper.py", line 18, in <module>
    CliWrapper.main()
  File "/usr/lib/python2.7/dist-packages/pyproject.py", line 388, in main
    commands.run(name, args)
  File "/usr/lib/python2.7/dist-packages/pyproject.py", line 261, in run
    command.module.main()
  File "/usr/lib/deckdebuild/pylib/cmd_deckdebuild.py", line 79, in main
    deckdebuild.deckdebuild(os.getcwd(), buildroot, outputdir, **conf)
  File "/usr/lib/deckdebuild/pylib/deckdebuild.py", line 75, in deckdebuild
    source_name = debsource.get_control_fields(path)['Source']
  File "/usr/lib/deckdebuild/pylib/debsource.py", line 20, in get_control_fields
    if line.strip() and not line.startswith(" ") ])
ValueError: dictionary update sequence element #6 has length 1; 2 is required
error: package `tklbam-squid=2.7.STABLE9-2.1turnkey+36+gebf182e' failed to build
````
Here's the relevant line from [`deckdebuild.py`](https://github.com/turnkeylinux/deckdebuild/blob/master/pylib/deckdebuild.py#L75):
````
source_name = debsource.get_control_fields(path)['Source']
````
And what that is calling ([`debsource.py`](https://github.com/turnkeylinux/deckdebuild/blob/master/pylib/debsource.py#L16-L20)):
````
def get_control_fields(path):
    controlfile = join(path, "debian/control")
    return dict([ re.split("\s*:\s+", line.strip(), 1)
                  for line in file(controlfile).readlines()
                  if line.strip() and not line.startswith(" ") ])
````
Finally, the diff between the current `master` and `lamby/packaging`:
````
diff --git a/debian/control b/debian/control
index 371d903..98a3e56 100644
--- a/debian/control
+++ b/debian/control
@@ -3,15 +3,30 @@ Section: web
 Priority: optional
 Maintainer: Luigi Gangitano <luigi@debian.org>
 Homepage: http://www.squid-cache.org/
-Standards-Version: 3.8.4
-Build-Depends: libldap2-dev, libpam0g-dev, sharutils, dpatch (>= 2.0.9), po-debconf, libdb-dev, libgssglue-dev, libkrb5-dev, hardening-wrapper, autotools-dev
+Standards-Version: 4.0.0
+Build-Depends:
+ autotools-dev,
+ debhelper (>= 10),
+ libdb-dev,
+ libgssglue-dev,
+ libkrb5-dev,
+ libldap2-dev,
+ libpam0g-dev,
+ po-debconf,
+ sharutils,
 
 Package: tklbam-squid
 Architecture: any
-Section: web
-Priority: optional
-Pre-Depends: debconf (>= 1.2.9) | debconf-2.0
-Depends: ${shlibs:Depends}, netbase, adduser, tklbam-squid-common (>= ${source:Version}), lsb-base (>= 3.2-14), turnkey-pylib
+Pre-Depends:
+ debconf (>= 1.2.9) | debconf-2.0,
+Depends:
+ adduser,
+ lsb-base (>= 3.2-14),
+ ${misc:Depends},
+ netbase,
+ tklbam-squid-common (>= ${source:Version}),
+ turnkey-pylib,
+ ${shlibs:Depends},
 Description: TKLBAM embedded Internet object cache (WWW proxy cache)
  This package provides the Squid Internet Object Cache developed by
  the National Laboratory for Applied Networking Research (NLANR) and
@@ -19,8 +34,8 @@ Description: TKLBAM embedded Internet object cache (WWW proxy cache)
 
 Package: tklbam-squid-common
 Architecture: any
-Section: web
-Priority: optional
+Depends:
+ ${misc:Depends},
 Description: TKLBAM embedded Internet object cache (WWW proxy cache) - common files
  This package provides the Squid Internet Object Cache developed by
  the National Laboratory for Applied Networking Research (NLANR) and
````

**Comment by JedMeister** [comment]
Actually, this can be closed now due to https://github.com/turnkeylinux/deckdebuild/commit/1f228b381e74e5ac00b80d5fbd6b503a60d951b7 and it should be backwards compatible, so should still work for the existing v14.2 apackages and Jessie in general.
