### ISSUE TITLE
current build infrastructure doesn't seem to provide virtual packages properly?!

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#916]
I'm currently working on the stretch transition and am hitting an issue:
````
root@da-shiz products/core# export RELEASE=debian/stretch
root@da-shiz products/core# export FAB_POOL=y
root@da-shiz products/core# make clean       
deck -D build/bootstrap
rm -rf build/root.spec build/cdroot build/product.iso build/log build/stamps
root@da-shiz products/core# make
deck /turnkey/fab/bootstraps/stretch build/bootstrap
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/apt build/bootstrap;
fab-chroot build/bootstrap --script /turnkey/fab/common/conf/turnkey.d/apt;
fab-chroot build/bootstrap "echo nameserver 8.8.8.8 > /etc/resolv.conf";
fab-chroot build/bootstrap "echo nameserver 8.8.4.4 >> /etc/resolv.conf";
touch build/stamps/bootstrap
unit_plans=""; fab-plan-resolve plan/main $unit_plans  --bootstrap=/turnkey/fab/bootstraps/stretch --output=build/root.spec -D 'FAB_ARCH=amd64' -D 'FAB_HTTP_PROXY=http://127.0.0.1:8124' -D 'AMD64=y' -D 'RELEASE=debian/stretch' -D 'DISTRO=debian' -D 'CODENAME=stretch' -D 'DEBIAN=y'
Traceback (most recent call last):
  File "/usr/lib/fab/wrapper.py", line 34, in <module>
    CliWrapper.main()
  File "/usr/lib/python2.7/dist-packages/pyproject.py", line 388, in main
    commands.run(name, args)
  File "/usr/lib/python2.7/dist-packages/pyproject.py", line 261, in run
    command.module.main()
  File "/usr/lib/fab/pylib/cmd_plan_resolve.py", line 131, in main
    spec = plan.resolve()
  File "/usr/lib/fab/pylib/plan.py", line 338, in resolve
    raise Error("broken dependencies: " + "\n".join(brokendeps))
plan.Error: broken dependencies: perl-openssl-abi-1.1 (libnet-ssleay-perl -> webmin -> plan/main)
/usr/share/fab/product.mk:526: recipe for target 'build/stamps/root.spec' failed
make: *** [build/stamps/root.spec] Error 1
````
So it can't find `perl-openssl-abi-1.1`. But that is actually only a virtual package supplied by `perl-openssl-defaults`. When I check chanko, it's already in there:
````
root@da-shiz chankos/stretch.chanko# chanko get perl-openssl-abi-1.1
Nothing to get...
root@da-shiz chankos/stretch.chanko# chanko get perl-openssl-defaults
Nothing to get...
root@da-shiz chankos/stretch.chanko# ls archives/ | grep perl-openssl
perl-openssl-defaults_3_amd64.deb
````

I'll work around it for now by excluding Webmin from the build, but we'll need to resolve that before we release v15.0.

**Comment by JedMeister** [comment]
FWIW, it's definitely an issue with our package building infrastructure. I just tested in a Stretch chroot:
````
root@da-shiz:/# apt-get update
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease            
Hit:3 http://cdn-fastly.deb.debian.org/debian stretch Release
Reading package lists... Done
root@da-shiz:/# apt-get install perl-openssl-defaults
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  perl-openssl-defaults
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 6782 B of archives.
After this operation, 27.6 kB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 perl-openssl-defaults amd64 3 [6782 B]
Fetched 6782 B in 1s (6524 B/s)              
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package perl-openssl-defaults:amd64.
(Reading database ... 31225 files and directories currently installed.)
Preparing to unpack .../perl-openssl-defaults_3_amd64.deb ...
Unpacking perl-openssl-defaults:amd64 (3) ...
Setting up perl-openssl-defaults:amd64 (3) ...
Processing triggers for man-db (2.7.6.1-2) ...
root@da-shiz:/# apt-cache policy  perl-openssl-abi*
perl-openssl-abi-1.1:
  Installed: (none)
  Candidate: (none)
  Version table:
root@da-shiz:/# apt-get install perl-openssl-abi-1.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'perl-openssl-defaults' instead of 'perl-openssl-abi-1.1'
perl-openssl-defaults is already the newest version (3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@da-shiz:/# apt-cache policy  perl-openssl-abi*
perl-openssl-abi-1.1:
  Installed: (none)
  Candidate: (none)
  Version table:
root@da-shiz:/# apt-get install libnet-ssleay-perl 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libnet-ssleay-perl
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 285 kB of archives.
After this operation, 1151 kB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libnet-ssleay-perl amd64 1.80-1 [285 kB]
Fetched 285 kB in 0s (299 kB/s)        
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libnet-ssleay-perl.
(Reading database ... 31235 files and directories currently installed.)
Preparing to unpack .../libnet-ssleay-perl_1.80-1_amd64.deb ...
Unpacking libnet-ssleay-perl (1.80-1) ...
Setting up libnet-ssleay-perl (1.80-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
root@da-shiz:/# apt-get purge perl-openssl-defaults
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  libnet-ssleay-perl* perl-openssl-defaults*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 1179 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 31355 files and directories currently installed.)
Removing libnet-ssleay-perl (1.80-1) ...
Removing perl-openssl-defaults:amd64 (3) ...
Processing triggers for man-db (2.7.6.1-2) ...
root@da-shiz:/# apt-get install libnet-ssleay-perl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  perl-openssl-defaults
The following NEW packages will be installed:
  libnet-ssleay-perl perl-openssl-defaults
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/292 kB of archives.
After this operation, 1179 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package perl-openssl-defaults:amd64.
(Reading database ... 31225 files and directories currently installed.)
Preparing to unpack .../perl-openssl-defaults_3_amd64.deb ...
Unpacking perl-openssl-defaults:amd64 (3) ...
Selecting previously unselected package libnet-ssleay-perl.
Preparing to unpack .../libnet-ssleay-perl_1.80-1_amd64.deb ...
Unpacking libnet-ssleay-perl (1.80-1) ...
Setting up perl-openssl-defaults:amd64 (3) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libnet-ssleay-perl (1.80-1) ...
````

**Comment by JedMeister** [comment]
Removing the webmin tag as it's not actually anything to do with that. It's just that that demonstrates the issue.

**Comment by JedMeister** [comment]
The workaround, is to explicitly note the dependency that provides the virtual package.

**Comment by JedMeister** [comment]
This issue is now exacerbated by a new type of virtual package that appear in Debian now. The only workaround that we've been able to implement so far is to manually install the relevant packages within a conf script.

**Comment by JedMeister** [comment]
This appears to be related to #1388 (which I just closed).

However, I think that this may still be an issue? I'll move to 18.0 and see how we go...

**Comment by maddyalex804** [comment]
Thanks for sharing such a detailed breakdown of the issue. It’s always interesting to see how dependencies and infrastructure can affect smooth execution. On a different note, if anyone here ever finds themselves needing a break from debugging and package issues, I highly recommend checking out [Custom Acrylic Pool Designs](https://www.aupool.net/). It’s a refreshing reminder of how elegant, well crafted systems like modern home pools can really deliver peace and clarity, just like a clean and stable build.
