### ISSUE TITLE
[Stretch] TKLBAM backup failing

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#962]
TKLBAM is not working on v15.0/Stretch.

```
Last full backup is too old, forcing full backup
A .
Cleanup of temporary directory /tmp/duplicity-MU6NGm-tempdir failed -
this is probably a bug.
Traceback (most recent call last):
  File "/usr/lib/tklbam/deps/bin/duplicity", line 1405, in <module>
    with_tempdir(main)
  File "/usr/lib/tklbam/deps/bin/duplicity", line 1398, in with_tempdir
    fn()
  File "/usr/lib/tklbam/deps/bin/duplicity", line 1368, in main
    full_backup(col_stats)
  File "/usr/lib/tklbam/deps/bin/duplicity", line 513, in full_backup
    globals.backend)
  File "/usr/lib/tklbam/deps/bin/duplicity", line 391, in write_multivol
    globals.gpg_profile, globals.volsize)
  File
"/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/gpg.py",
line 316, in GPGWriteFile
    bytes_to_go = data_size - get_current_size()
  File
"/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/gpg.py",
line 308, in get_current_size
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory:
'/tmp/duplicity-MU6NGm-tempdir/mktemp-4wEhn_-2'

close failed in file object destructor:
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/bin/tklbam-backup", line 510, in <module>
    main()
  File "/usr/bin/tklbam-backup", line 464, in main
    log=_print)
  File "/usr/lib/tklbam/duplicity.py", line 268, in __call__
    backup_command.run(target.secret, target.credentials, debug=debug)
  File "/usr/lib/tklbam/duplicity.py", line 114, in run
    raise Error("non-zero exitcode (%d) from backup command: %s" %
(exitcode, str(self)))
duplicity.Error: non-zero exitcode (30) from backup command: duplicity
--verbosity=5 --volsize=25 --full-if-older-than=1M
--gpg-options=--cipher-algo=aes --include=/TKLBAM
--include-filelist=/TKLBAM/fsdelta-olist --exclude=**
--archive-dir=/var/cache/duplicity --s3-unencrypted-connection
--allow-source-mismatch /
s3://s3-ap-southeast-2.amazonaws.com/tklbam-ap-southeast-2-
34b10189773e284b420f/2si5ylw6ahmqkspw
```

Full TKLBAM output (including above stacktrace) from 'tklbam-backup' v15.0beta Core is attached (although probably irrelevant) [01tklbam-stacktrace.txt].

v15.0 Core TKLBAM profile attached (highly unlikely that it's relevant to the problem, but will be required for testing) [turnkey-core-15.0beta1-stretch-amd64.tar.gz]

It was suggested at one point that perhaps it's because /tmp isn't mounted as tmpfs, but I doubt that's the cause as it isn't in v14.x either.

It appears to be an issue with the old version of Duplicity we use. I assume that it must be something that has changed in Python2 between Jessie ([2.7.9](https://packages.debian.org/jessie/python)) and Stretch ([2.7.13](https://packages.debian.org/stretch/python)). FWIW I tried using the version of Duplicity in Stretch (details below) but it just raises new/different issues.

----

Duplicity from Stretch is [v0.7.11](https://packages.debian.org/stretch/duplicity)
Our fork appears to be [v0.6.18](https://github.com/turnkeylinux/tklbam-duplicity/blob/master/CHANGELOG)

As noted above, I tried installing Debian duplicity. It changes the issue, but doesn't fix it. It now appears to be boto related. See [02duplicity-stacktrace.txt]

Initially I tried linking tklbam-python-boto, but that didn't help either. See [03link-boto-stacktrace.txt]

I then tried installing Debian python-boto but that didn't help either. See [04install-python-boto.txt] & [05boto-stacktrace.txt].

It seems like the new errors are related to authentication, so are likely irrelevant to the original issue?!

----

And here is Liraz's feedback:

>This doesn't look like a problem in TKLBAM but in an interaction between
Stretch and the old version of Duplicity that TKLBAM installs as a
dependency.  Probably because the python version has changed. I can't debug
it from a stack trace. ‏ the way to debug this would be to put a breakpoint
right before the exception is raised. And then explore interactively
what's going on. Once we understand the issue fixing it should be quite
simple

## files

[01tklbam-stacktrace.txt](https://github.com/turnkeylinux/tracker/files/1460083/01tklbam-stacktrace.txt)
[02duplicty-stacktrace.txt](https://github.com/turnkeylinux/tracker/files/1460084/02duplicty-stacktrace.txt)
[03link-boto-stacktrace.txt](https://github.com/turnkeylinux/tracker/files/1460085/03link-boto-stacktrace.txt)
[04install-python-boto.txt](https://github.com/turnkeylinux/tracker/files/1460086/04install-python-boto.txt)
[05boto-stacktrace.txt](https://github.com/turnkeylinux/tracker/files/1460087/05boto-stacktrace.txt)
[turnkey-core-15.0beta1-stretch-amd64.tar.gz](https://github.com/turnkeylinux/tracker/files/1460080/turnkey-core-15.0beta1-stretch-amd64.tar.gz)

**Comment by DocCyblade** [comment]
@JedMeister - So I had a good debug session and the error is that function `get_current_size()` is trying to look at the temp directory (in the case  above`/tmp/duplicity-MU6NGm-tempdir/mktemp-4wEhn_-2`) and the directory does not exist, throwing the error.

After some hard core command line debugging using pdb (see below) it seems there is an error and it's doing a clean up due a GNUPG issue. With a little more digging it seems GnuPG is not installed ?

So I ran `apt-get install gnupg` and that seemed to fixed the issue. 

One of the changes in stretch was [Move to "Modern" GnuPG](https://www.debian.org/releases/stable/amd64/release-notes/ch-whats-new.en.html#modern-gnupg)

```
root@core ~# tklbam backup
Implicit --resume: Detected a rerun of an aborted backup session
                   You can disable this with the --disable-resume option

ATTEMPTING TO RESUME ABORTED BACKUP SESSION

UNCOMPRESSED BACKUP SIZE: 17.52 MB in 210 files

Executing Duplicity to backup system changes to encrypted, incremental archives
===============================================================================

# export PASSPHRASE=$(cat /var/lib/tklbam/secret)
# duplicity --verbosity=5 --volsize=25 --full-if-older-than=1M --gpg-options=--cipher-algo=aes --include=/TKLBAM --include-filelist=/TKLBAM/fsdelta-olist --exclude=** --archive-dir=/var/cache/duplicity --s3-unencrypted-connection --allow-source-mismatch / s3://s3.amazonaws.com/tklbam-us-east-1-7ad0c6e6e508e29f18be/23fbefh32w6blozf
Listing s3://s3.amazonaws.com/tklbam-us-east-1-7ad0c6e6e508e29f18be/23fbefh32w6blozf
Local and Remote metadata are synchronized, no sync needed.
Listing s3://s3.amazonaws.com/tklbam-us-east-1-7ad0c6e6e508e29f18be/23fbefh32w6blozf
Last full backup date: none
Last full backup is too old, forcing full backup
> /usr/lib/tklbam/deps/bin/duplicity(392)write_multivol()
-> if globals.encryption:
(Pdb) n
> /usr/lib/tklbam/deps/bin/duplicity(393)write_multivol()
-> at_end = gpg.GPGWriteFile(tarblock_iter, tdp.name,
(Pdb) n
> /usr/lib/tklbam/deps/bin/duplicity(394)write_multivol()
-> globals.gpg_profile, globals.volsize)
(Pdb) n
A .
A TKLBAM
A TKLBAM/backup-conf
A TKLBAM/etc
A TKLBAM/etc/group
A TKLBAM/etc/passwd
A TKLBAM/fsdelta
A TKLBAM/fsdelta-olist
A TKLBAM/newpkgs
A etc
A etc/.etckeeper
A etc/.git
A etc/.git/COMMIT_EDITMSG
A etc/.git/HEAD
A etc/.git/config
A etc/.git/description
A etc/.git/hooks
A etc/.git/hooks/applypatch-msg.sample
A etc/.git/hooks/commit-msg.sample
A etc/.git/hooks/post-update.sample
A etc/.git/hooks/pre-applypatch.sample
A etc/.git/hooks/pre-commit
A etc/.git/hooks/pre-commit.sample
A etc/.git/hooks/pre-push.sample
A etc/.git/hooks/pre-rebase.sample
A etc/.git/hooks/pre-receive.sample
A etc/.git/hooks/prepare-commit-msg.sample
A etc/.git/hooks/update.sample
A etc/.git/index
GPGError: GPGError...====\n',)
> /usr/lib/tklbam/deps/bin/duplicity(394)write_multivol()
-> globals.gpg_profile, globals.volsize)
(Pdb) n
--Return--
> /usr/lib/tklbam/deps/bin/duplicity(394)write_multivol()->None
-> globals.gpg_profile, globals.volsize)
(Pdb) n
GPGError: GPGError...====\n',)
> /usr/lib/tklbam/deps/bin/duplicity(516)full_backup()
-> globals.backend)
(Pdb) n
--Return--
> /usr/lib/tklbam/deps/bin/duplicity(516)full_backup()->None
-> globals.backend)
(Pdb) n
GPGError: GPGError...====\n',)
> /usr/lib/tklbam/deps/bin/duplicity(1371)main()
-> full_backup(col_stats)
(Pdb) n
--Return--
> /usr/lib/tklbam/deps/bin/duplicity(1371)main()->None
-> full_backup(col_stats)
(Pdb) n
GPGError: GPGError...====\n',)
> /usr/lib/tklbam/deps/bin/duplicity(1401)with_tempdir()
-> fn()
(Pdb) n
> /usr/lib/tklbam/deps/bin/duplicity(1403)with_tempdir()
-> tempdir.default().cleanup()
(Pdb) n
--Return--
> /usr/lib/tklbam/deps/bin/duplicity(1403)with_tempdir()->None
-> tempdir.default().cleanup()
(Pdb) n
GPGError: GPGError...====\n',)
> /usr/lib/tklbam/deps/bin/duplicity(1408)<module>()
-> with_tempdir(main)
(Pdb) p 
*** SyntaxError: SyntaxError('unexpected EOF while parsing', ('<string>', 0, 0, ''))
(Pdb) l
1403 	        tempdir.default().cleanup()
1404 	
1405 	
1406 	if __name__ == "__main__":
1407 	    try:
1408 ->	        with_tempdir(main)
1409 	
1410 	    # Don't move this lower.  In order to get an exit
1411 	    # status out of the system, you have to call the
1412 	    # sys.exit() function.  Python handles this by
1413 	    # raising the SystemExit exception.  Cleanup code
(Pdb) n
> /usr/lib/tklbam/deps/bin/duplicity(1415)<module>()
-> except SystemExit, e:
(Pdb) p
*** SyntaxError: SyntaxError('unexpected EOF while parsing', ('<string>', 0, 0, ''))
(Pdb) l
1410 	    # Don't move this lower.  In order to get an exit
1411 	    # status out of the system, you have to call the
1412 	    # sys.exit() function.  Python handles this by
1413 	    # raising the SystemExit exception.  Cleanup code
1414 	    # goes here, if needed.
1415 ->	    except SystemExit, e:
1416 	        # No traceback, just get out
1417 	        sys.exit(e)
1418 	
1419 	    except KeyboardInterrupt, e:
1420 	        # No traceback, just get out
(Pdb) l
1421 	        log.Info(_("INT intercepted...exiting."))
1422 	        sys.exit(4)
1423 	
1424 	    except gpg.GPGError, e:
1425 	        # For gpg errors, don't show an ugly stack trace by
1426 	        # default. But do with sufficient verbosity.
1427 	        log.Info(_("GPG error detail: %s")
1428 	                 % (''.join(traceback.format_exception(*sys.exc_info()))))
1429 	        log.FatalError("%s: %s" % (e.__class__.__name__, e.args[0]),
1430 	                       log.ErrorCode.gpg_failed,
1431 	                       e.__class__.__name__)
(Pdb) n
> /usr/lib/tklbam/deps/bin/duplicity(1419)<module>()
-> except KeyboardInterrupt, e:
(Pdb) n
> /usr/lib/tklbam/deps/bin/duplicity(1424)<module>()
-> except gpg.GPGError, e:
(Pdb) p
*** SyntaxError: SyntaxError('unexpected EOF while parsing', ('<string>', 0, 0, ''))
(Pdb) l
1419 	    except KeyboardInterrupt, e:
1420 	        # No traceback, just get out
1421 	        log.Info(_("INT intercepted...exiting."))
1422 	        sys.exit(4)
1423 	
1424 ->	    except gpg.GPGError, e:
1425 	        # For gpg errors, don't show an ugly stack trace by
1426 	        # default. But do with sufficient verbosity.
1427 	        log.Info(_("GPG error detail: %s")
1428 	                 % (''.join(traceback.format_exception(*sys.exc_info()))))
1429 	        log.FatalError("%s: %s" % (e.__class__.__name__, e.args[0]),
(Pdb) n
> /usr/lib/tklbam/deps/bin/duplicity(1427)<module>()
-> log.Info(_("GPG error detail: %s")
(Pdb) l
1422 	        sys.exit(4)
1423 	
1424 	    except gpg.GPGError, e:
1425 	        # For gpg errors, don't show an ugly stack trace by
1426 	        # default. But do with sufficient verbosity.
1427 ->	        log.Info(_("GPG error detail: %s")
1428 	                 % (''.join(traceback.format_exception(*sys.exc_info()))))
1429 	        log.FatalError("%s: %s" % (e.__class__.__name__, e.args[0]),
1430 	                       log.ErrorCode.gpg_failed,
1431 	                       e.__class__.__name__)
1432 	
(Pdb) n
> /usr/lib/tklbam/deps/bin/duplicity(1428)<module>()
-> % (''.join(traceback.format_exception(*sys.exc_info()))))
(Pdb) l
1423 	
1424 	    except gpg.GPGError, e:
1425 	        # For gpg errors, don't show an ugly stack trace by
1426 	        # default. But do with sufficient verbosity.
1427 	        log.Info(_("GPG error detail: %s")
1428 ->	                 % (''.join(traceback.format_exception(*sys.exc_info()))))
1429 	        log.FatalError("%s: %s" % (e.__class__.__name__, e.args[0]),
1430 	                       log.ErrorCode.gpg_failed,
1431 	                       e.__class__.__name__)
1432 	
1433 	    except duplicity.errors.UserError, e:
(Pdb) n
GPG error detail: Traceback (most recent call last):
  File "/usr/lib/tklbam/deps/bin/duplicity", line 1408, in <module>
    with_tempdir(main)
  File "/usr/lib/tklbam/deps/bin/duplicity", line 1401, in with_tempdir
    fn()
  File "/usr/lib/tklbam/deps/bin/duplicity", line 1371, in main
    full_backup(col_stats)
  File "/usr/lib/tklbam/deps/bin/duplicity", line 516, in full_backup
    globals.backend)
  File "/usr/lib/tklbam/deps/bin/duplicity", line 394, in write_multivol
    globals.gpg_profile, globals.volsize)
  File "/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/gpg.py", line 323, in GPGWriteFile
    file.write(data)
  File "/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/gpg.py", line 185, in write
    self.gpg_failed()
  File "/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/gpg.py", line 206, in gpg_failed
    raise GPGError, msg
GPGError: GPG Failed, see log below:
===== Begin GnuPG log =====
Traceback (most recent call last):
File "/usr/lib/tklbam/deps/bin/duplicity", line 1408, in <module>
with_tempdir(main)
File "/usr/lib/tklbam/deps/bin/duplicity", line 1403, in with_tempdir
tempdir.default().cleanup()
File "/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/tempdir.py", line 229, in cleanup
try:
File "/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/tempdir.py", line 229, in cleanup
try:
File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
return self.dispatch_line(frame)
File "/usr/lib/python2.7/bdb.py", line 68, in dispatch_line
if self.quitting: raise BdbQuit
BdbQuit

===== End GnuPG log =====


> /usr/lib/tklbam/deps/bin/duplicity(1429)<module>()
-> log.FatalError("%s: %s" % (e.__class__.__name__, e.args[0]),
(Pdb) n 
> /usr/lib/tklbam/deps/bin/duplicity(1430)<module>()
-> log.ErrorCode.gpg_failed,
(Pdb) n
> /usr/lib/tklbam/deps/bin/duplicity(1431)<module>()
-> e.__class__.__name__)
(Pdb) n
GPGError: GPG Failed, see log below:
===== Begin GnuPG log =====
Traceback (most recent call last):
File "/usr/lib/tklbam/deps/bin/duplicity", line 1408, in <module>
with_tempdir(main)
File "/usr/lib/tklbam/deps/bin/duplicity", line 1403, in with_tempdir
tempdir.default().cleanup()
File "/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/tempdir.py", line 229, in cleanup
try:
File "/usr/lib/tklbam/deps/lib/python2.7/dist-packages/duplicity/tempdir.py", line 229, in cleanup
try:
File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
return self.dispatch_line(frame)
File "/usr/lib/python2.7/bdb.py", line 68, in dispatch_line
if self.quitting: raise BdbQuit
BdbQuit

===== End GnuPG log =====

SystemExit: 31
> /usr/lib/tklbam/deps/bin/duplicity(1431)<module>()
-> e.__class__.__name__)
(Pdb) n
--Return--
> /usr/lib/tklbam/deps/bin/duplicity(1431)<module>()->None
-> e.__class__.__name__)
(Pdb) n
Cleanup of temporary directory /var/cache/duplicity/f235c0e831c726750e1804a6553bc273/duplicity-K7nld4-tempdir failed - this is probably a bug.
Cleanup of temporary directory /var/cache/duplicity/f235c0e831c726750e1804a6553bc273/duplicity-8s28Fb-tempdir failed - this is probably a bug.
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <function _remove at 0x7f09c3f366e0> ignored
Traceback (most recent call last):
  File "/usr/bin/tklbam", line 46, in <module>
    CliWrapper.main()
  File "/usr/lib/tklbam/cliwrapper.py", line 88, in main
    commands[command].main()
  File "/usr/lib/tklbam/cmd_backup.py", line 464, in main
    log=_print)
  File "/usr/lib/tklbam/duplicity.py", line 268, in __call__
    backup_command.run(target.secret, target.credentials, debug=debug)
  File "/usr/lib/tklbam/duplicity.py", line 114, in run
    raise Error("non-zero exitcode (%d) from backup command: %s" % (exitcode, str(self)))
duplicity.Error: non-zero exitcode (31) from backup command: duplicity --verbosity=5 --volsize=25 --full-if-older-than=1M --gpg-options=--cipher-algo=aes --include=/TKLBAM --include-filelist=/TKLBAM/fsdelta-olist --exclude=** --archive-dir=/var/cache/duplicity --s3-unencrypted-connection --allow-source-mismatch / s3://s3.amazonaws.com/tklbam-us-east-1-7ad0c6e6e508e29f18be/23fbefh32w6blozf

```

**Comment by JedMeister** [comment]
Awesome detective work @DocCyblade ! I can't believe that it was that simple (yet so hard to find). It sounds like your gut feeling that it was GPG related was totally on the money!

Mega brownie points for you!

**Comment by JedMeister** [comment]
closed with https://github.com/turnkeylinux/common/commit/69155da624a9a13c05eeb3c40a7b84e30daa5760

**Comment by JedMeister** [comment]
Also added to the `tklbam` package (as I should have initially!):

https://github.com/turnkeylinux/tklbam/commit/7fb66b89bf954eb086b771d14dc9ec9a46f4c5e8
